### ISSUE TITLE
Sub navigation doesn't import SCSS file

### ISSUE THREAD

**Issue by john-brown-bjss** [NHSDigital/nhsuk-react-components-extensions#5]
When using the sub-navigation component in a project the styling doesn't come with the component.

A work-around was created by importing the component css into my apps App.scss file:

> @import "~nhsuk-react-components-extensions/css/components.css";

The fix needs to import the SCSS file into the component.

**Comment by Tomdango** [comment]
Hi John, I think this might be a wont-fix as this is a fairly standard pattern. We did look into coupling the styling with the component but it caused issues when the components were transpiled by Babel. This occurred because the component was still trying to directly import the scss file in the project, that didn't exist in the final build.

Do you two have any other thoughts? @lukepearson @VirtualVirtuoso

**Comment by john-brown-bjss** [comment]
Okay that makes sense - I guess it's following a similar pattern to front-end styles. Might be a good idea to potentially update the storybook with an installation tab which explains where to import the styling.

**Comment by Tomdango** [comment]
I've opened https://github.com/NHSDigital/nhsuk-react-components-extensions/pull/6 which adds documentation for the usage of styles, installation and imports.

**Comment by Tomdango** [comment]
#6 has been merged - closing this issue as resolved.
